Repository cta-observatory/ctapipe, pull requests merged in 2019-10, with the labels that each got.

#1125 ensure gain selection returns uint8, not 64-bit int
  ctapipe/calib/camera/gainselection.py
Labels: performance, ready for review

#1126 a few small random cleanups
  .gitignore
  ctapipe/calib/camera/__init__.py
  ctapipe/image/cleaning.py
  environment.yml
  py3.6_env.yaml
  py3.7_env.yaml
  setup.cfg
Labels: ready for review

#1136 Ci warnings
  ctapipe/calib/camera/tests/test_gainselection.py
  ctapipe/core/tool.py
  ctapipe/reco/regressor_classifier_base.py
  ctapipe/tools/extract_charge_resolution.py
  ctapipe/tools/plot_charge_resolution.py
  ctapipe/utils/datasets.py
  ctapipe/visualization/bokeh.py
  environment.yml
  py3.6_env.yaml
  py3.7_env.yaml
  setup.py
Labels: enhancement, ready for review

#1128 Use astropys own version of quantity_approx
  ctapipe/image/tests/test_hillas.py
Labels: ready for review

#1129 TelescopeParameter Trait
  ctapipe/core/tests/test_traits.py
  ctapipe/core/traits.py
Labels: ready for review

#1124 Fix/core tool
  ctapipe/core/tool.py
Labels: ready for review

#1137 Also test ctapipe with a pure pip installation (no conda)
  .travis.yml
  ci/install.sh
  docs/tutorials/coordinates_example.ipynb
  docs/tutorials/ground_frame.png
  docs/tutorials/tilted_ground_frame.png
  setup.py
Labels: ready for review

#1143 Improve extract_pulse_time_around_peak to ignore negative samples
  ctapipe/image/extractor.py
  ctapipe/image/tests/test_extractor.py
Labels: algorithm, ready for review

#1123 Improvements to Container classes
  ctapipe/core/__init__.py
  ctapipe/core/container.py
  ctapipe/core/tests/test_container.py
  ctapipe/core/traits.py
  ctapipe/image/concentration.py
  ctapipe/image/leakage.py
  ctapipe/image/tests/test_concentration.py
  ctapipe/image/tests/test_leakage.py
  ctapipe/io/containers.py
  ctapipe/io/eventsource.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_hdf5.py
  docs/tutorials/lst_analysis_bootcamp_2018.ipynb
Labels: API change, ready for review

#1156 fixed bug in TelescopeParameterResolver
  ctapipe/core/traits.py
Labels: bug

#1141 Pointing container
  ctapipe/io/hessioeventsource.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_simteleventsource.py
  ctapipe/reco/tests/test_HillasReconstructor.py
  ctapipe/reco/tests/test_hillas_intersection.py
  ctapipe/reco/tests/test_reconstruction_methods.py
Labels: ready for review

#1158 Add resolving to the TelescopeParameter
  ctapipe/core/tests/test_traits.py
  ctapipe/core/traits.py
Labels: ready for review
