Repository cta-observatory/ctapipe, pull requests merged in 2020-04, with the labels that each got.

#1244 Waveform toy model
  ctapipe/image/tests/test_toy.py
  ctapipe/image/toymodel.py
  ctapipe/instrument/camera/readout.py
Labels: algorithm, ready for review

#1027 Fix tests for Tools, fixes #1214
  .travis.yml
  ctapipe/core/__init__.py
  ctapipe/core/tests/test_tool.py
  ctapipe/core/tool.py
  ctapipe/tools/dump_instrument.py
  ctapipe/tools/muon_reconstruction.py
  ctapipe/tools/tests/test_tools.py
  docs/examples/Tools.ipynb
Labels: enhancement, ready for review

#1253 Muon refactoring
  ctapipe/containers.py
  ctapipe/image/muon/__init__.py
  ctapipe/image/muon/muon_reco_functions.py
  ctapipe/image/muon/muon_ring_finder.py
  ctapipe/image/muon/ring_fitter.py
  ctapipe/image/muon/tests/test_ring_fitter.py
Labels: API change, enhancement, muons, ready for review

#1276 Fix bug in ImageExtractor and WaveformModel concerning waveform sampling rate
  ctapipe/calib/camera/tests/test_calibrator.py
  ctapipe/calib/camera/tests/test_flatfield.py
  ctapipe/calib/camera/tests/test_pedestals.py
  ctapipe/image/extractor.py
  ctapipe/image/tests/test_extractor.py
  ctapipe/image/tests/test_toy.py
  ctapipe/image/toymodel.py
Labels: bug, calibration, ready for review

#1254 Remove unused and untested muon fitting code
  ctapipe/image/muon/fitting.py
  docs/bibliography.rst
Labels: muons, refactoring

#1221 CTA Reference Metadata handling
  ctapipe/core/tests/test_traits.py
  ctapipe/core/traits.py
  ctapipe/io/metadata.py
  ctapipe/io/tests/test_metadata.py
  docs/bibliography.rst
  docs/ctapipe_api/io/index.rst
Labels: core, new functionality, ready for review

#1261 Muon intensity improvements
  ctapipe/containers.py
  ctapipe/image/muon/__init__.py
  ctapipe/image/muon/features.py
  ctapipe/image/muon/intensity_fitter.py
  ctapipe/image/muon/muon_integrator.py
  ctapipe/image/muon/muon_reco_functions.py
  ctapipe/image/muon/tests/test_intensity_fit.py
  ctapipe/image/muon/tests/test_muon_features.py
  ctapipe/image/muon/tests/test_muon_integrator.py
  ctapipe/image/muon/tests/test_muon_reco.py
  ctapipe/tools/muon_reconstruction.py
  ctapipe/tools/tests/test_tools.py
Labels: muons, refactoring

#1121 Added tailcuts data volume reducer
  ctapipe/calib/camera/calibrator.py
  ctapipe/core/traits.py
  ctapipe/image/cleaning.py
  ctapipe/image/reducer.py
  ctapipe/image/tests/test_reducer.py
Labels: algorithm

#1283 Update documentation for CameraCalibrator and ImageExtractor
  docs/ctapipe_api/calib/index.rst
  docs/ctapipe_api/calib/index_camera.rst
  docs/ctapipe_api/image/extractor.rst
Labels: documentation, ready for review
