Repository cta-observatory/ctapipe, pull requests merged in 2020-10, with the labels that each got.

#1427 add function to get astropy table from ctapipe hdf5 file
  ctapipe/io/astropy_helpers.py
  ctapipe/io/tests/test_astropy_helpers.py
Labels: enhancement, ready for review

#1442 Fix loss of performance in TwoPassWindowSum
  ctapipe/image/extractor.py
  docs/ctapipe_api/image/TwoPassWindowSum_1st_pass_example.png
  docs/ctapipe_api/image/extractor.rst
Labels: calibration, physics

#1467 Require python >= 3.7
  .travis.yml
  ci/install.sh
  docs/index.rst
  setup.py
Labels: ready for review

#1476 Add correct frame to CameraGeometry in SubArrayDescription.from_hdf, fixes #1469
  ctapipe/instrument/subarray.py
  ctapipe/instrument/tests/test_subarray.py
Labels: ready for review

#1473 Use traits for TelescopeParameter
  ctapipe/core/tests/test_traits.py
  ctapipe/core/traits.py
Labels: ready for review

#1479 Do not write tels with trigger in pointing table
  ctapipe/tools/stage1.py
  ctapipe/tools/tests/test_tools.py
Labels: ready for review

#1477 (Re)move trigger related fields from R0/R1/DL0 Container
  .gitignore
  ctapipe/calib/camera/flatfield.py
  ctapipe/calib/camera/pedestals.py
  ctapipe/calib/camera/tests/test_flatfield.py
  ctapipe/calib/camera/tests/test_pedestals.py
  ctapipe/containers.py
  ctapipe/io/simteleventsource.py
  ctapipe/tools/stage1.py
Labels: ready for review

#1481 Fix Path.validate for None
  ctapipe/core/tests/test_traits.py
  ctapipe/core/traits.py
Labels: ready for review

#1485 Update maintainer info, fixes #1466
  docs/development/maintainer-info.rst
Labels: ready for review

#1444 Remove need for `add_subcomponent` include subcomponents in Component.get_current_config
  ctapipe/core/component.py
  ctapipe/core/tests/test_component.py
  ctapipe/core/tests/test_tool.py
  ctapipe/core/tool.py
  ctapipe/tools/display_dl1.py
  ctapipe/tools/display_events_single_tel.py
  ctapipe/tools/display_integrator.py
  ctapipe/tools/extract_charge_resolution.py
  ctapipe/tools/muon_reconstruction.py
  ctapipe/tools/plot_charge_resolution.py
  ctapipe/tools/stage1.py
  docs/examples/Tools.ipynb
  examples/simple_event_writer.py
  examples/tool_example.py
Labels: ready for review

#1358 support user table in OpticsDescription.from_name
  ctapipe/instrument/optics.py
  ctapipe/instrument/tests/test_optics.py
Labels: ready for review

#1471 Fix bug in h5_table_to_astropy and HDF5TableWriter
  ctapipe/io/__init__.py
  ctapipe/io/astropy_helpers.py
  ctapipe/io/hdf5tableio.py
  ctapipe/io/tests/test_astropy_helpers.py
Labels: ready for review
