Repository cta-observatory/ctapipe, pull requests merged in 2020-05, with the labels that each got.

#1215 2-Pass waveform integration à-la-CTA/MARS
  CODEOWNERS
  ctapipe/image/extractor.py
  ctapipe/image/tests/test_extractor.py
Labels: algorithm, calibration, enhancement

#1256 Calculate ring containment analytically
  ctapipe/image/muon/features.py
  ctapipe/image/muon/tests/test_muon_features.py
  ctapipe/tools/muon_reconstruction.py
Labels: algorithm, muons

#1163 DL1 writer tool (ctapipe-stage1-process)
  ci/install.sh
  ctapipe/containers.py
  ctapipe/core/tool.py
  ctapipe/image/__init__.py
  ctapipe/image/cleaning.py
  ctapipe/image/extractor.py
  ctapipe/image/morphology.py
  ctapipe/image/statistics.py
  ctapipe/image/tests/test_cleaning.py
  ctapipe/image/tests/test_morphology.py
  ctapipe/image/tests/test_timing_parameters.py
  ctapipe/image/timing.py
  ctapipe/instrument/subarray.py
  ctapipe/instrument/tests/test_subarray.py
  ctapipe/io/hdf5tableio.py
  ctapipe/io/metadata.py
  ctapipe/io/tableio.py
  ctapipe/tools/stage1.py
  ctapipe/tools/tests/test_tools.py
  ctapipe/visualization/tests/test_mpl.py
  docs/_static/theme_overrides.css
  docs/conf.py
  docs/data_models/dl1.rst
  docs/data_models/index.rst
  docs/index.rst
  docs/tutorials/lst_analysis_bootcamp_2018.ipynb
  environment.yml
  examples/plot_array_hillas.py
  examples/stage1_config.json
  setup.py
Labels: chain, new functionality
