Repository cta-observatory/ctapipe, pull requests merged in 2020-11, with the labels that each got.

#1447 Dl1 merge tool
  ctapipe/tools/dl1_merge.py
  ctapipe/tools/tests/test_tools.py
  environment.yml
  setup.py
Labels: ready for review

#1495 Refactor simulation event info
  ctapipe/calib/camera/flatfield.py
  ctapipe/calib/camera/pedestals.py
  ctapipe/calib/camera/tests/test_calibrator.py
  ctapipe/calib/camera/tests/test_flatfield.py
  ctapipe/calib/camera/tests/test_pedestals.py
  ctapipe/containers.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_hdf5.py
  ctapipe/io/tests/test_simteleventsource.py
  ctapipe/io/toymodel.py
  ctapipe/plotting/bokeh_event_viewer.py
  ctapipe/reco/tests/test_HillasReconstructor.py
  ctapipe/reco/tests/test_hillas_intersection.py
  ctapipe/reco/tests/test_reconstruction_methods.py
  ctapipe/tools/display_events_single_tel.py
  ctapipe/tools/display_integrator.py
  ctapipe/tools/display_summed_images.py
  ctapipe/tools/extract_charge_resolution.py
  ctapipe/tools/muon_reconstruction.py
  ctapipe/tools/stage1.py
  ctapipe/visualization/mpl_array.py
  docs/data_models/dl1.rst
  docs/examples/containers.ipynb
  docs/examples/table_writer_reader.ipynb
  docs/tutorials/calibrated_data_exploration.ipynb
  docs/tutorials/coordinates_example.ipynb
  docs/tutorials/ctapipe_handson.ipynb
  docs/tutorials/lst_analysis_bootcamp_2018.ipynb
  docs/tutorials/raw_data_exploration.ipynb
  docs/tutorials/theta_square.ipynb
  examples/plot_array_hillas.py
  examples/plot_theta_square.py
  examples/simple_event_writer.py
  examples/stereo_reconstruction.py
Labels: API change, ready for review

#1496 Add camera frame in TelescopeDescription.from_name
  ctapipe/instrument/telescope.py
Labels: ready for review

#1491 Use enum for pixel shapes
  ctapipe/instrument/__init__.py
  ctapipe/instrument/camera/__init__.py
  ctapipe/instrument/camera/geometry.py
  ctapipe/instrument/camera/tests/test_geometry.py
  ctapipe/visualization/mpl_camera.py
  ctapipe/visualization/tests/test_mpl.py
Labels: API change, enhancement, ready for review

#1492 Make time shift corrections optional
  ctapipe/calib/camera/calibrator.py
  ctapipe/calib/camera/tests/test_calibrator.py
Labels: ready for review

#1475 Run tools in tmpdir during tests, do not write provlog if only help was run
  ctapipe/core/tests/test_tool.py
  ctapipe/core/tool.py
  ctapipe/tools/tests/test_tools.py
Labels: ready for review

#1357 Dl1 event source
  ctapipe/io/__init__.py
  ctapipe/io/dl1eventsource.py
  ctapipe/io/eventsource.py
  ctapipe/io/hdf5tableio.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_dl1eventsource.py
  ctapipe/io/tests/test_event_source.py
  ctapipe/io/tests/test_simteleventsource.py
  ctapipe/io/toymodel.py
  ctapipe/tools/stage1.py
  ctapipe/tools/tests/test_tools.py
  ctapipe/utils/__init__.py
  ctapipe/utils/index_finder.py
  ctapipe/utils/tests/test_index_finder.py
Labels: Breaking change, ready for review

#1499 Create a DL1Writer and ImageProcessor to simplify stage1
  ctapipe/containers.py
  ctapipe/core/provenance.py
  ctapipe/image/__init__.py
  ctapipe/image/concentration.py
  ctapipe/image/image_processor.py
  ctapipe/image/leakage.py
  ctapipe/image/tests/test_concentration.py
  ctapipe/image/tests/test_image_processor.py
  ctapipe/image/tests/test_leakage.py
  ctapipe/io/__init__.py
  ctapipe/io/dl1eventsource.py
  ctapipe/io/dl1writer.py
  ctapipe/io/tests/test_dl1eventsource.py
  ctapipe/io/tests/test_dl1writer.py
  ctapipe/tools/stage1.py
  ctapipe/tools/tests/test_tools.py
  docs/ctapipe_api/io/index.rst
  docs/data_models/dl1.rst
  docs/index.rst
  docs/tools/index.rst
  docs/tutorials/lst_analysis_bootcamp_2018.ipynb
  environment.yml
  examples/stage1_config.json
  setup.cfg
  setup.py
Labels: ready for review

#1310 Add --quiet/-q option and --logfile
  .travis.yml
  ctapipe/core/logging.py
  ctapipe/core/tests/test_tool.py
  ctapipe/core/tool.py
  ctapipe/io/hdf5tableio.py
  ctapipe/tools/camdemo.py
  ctapipe/utils/datasets.py
Labels: ready for review

#1334 Use setuptools_scm for versioning, fixes #1333
  .gitignore
  MANIFEST.in
  ctapipe/__init__.py
  ctapipe/_dev_version.py
  ctapipe/version.py
  pyproject.toml
  setup.py
Labels: ready for review

#1451 dump CameraReadout files in ctapipe-dump-instrument
  ctapipe/instrument/tests/test_optics.py
  ctapipe/tools/dump_instrument.py
  ctapipe/tools/tests/test_tools.py
Labels: enhancement, ready for review

#1465 Apply time calib simtel
  ctapipe/io/simteleventsource.py
  ctapipe/tools/display_dl1.py
Labels: ready for review

#1498 Download test files
  ctapipe/conftest.py
  ctapipe/core/tests/test_tool.py
  ctapipe/instrument/camera/tests/test_description.py
  ctapipe/io/tests/test_event_source.py
  ctapipe/tools/info.py
  ctapipe/tools/tests/test_tools.py
  ctapipe/utils/datasets.py
  ctapipe/utils/download.py
  ctapipe/utils/tests/test_datasets.py
  docs/examples/Tools.ipynb
  environment.yml
  setup.py
Labels: ready for review

#1551 Update MergerTool examples, adding allowed_tels and tests. Fixes #1533 and #1534
  ctapipe/tools/dl1_merge.py
  ctapipe/tools/tests/test_tools.py
Labels: ready for review
