Repository cta-observatory/ctapipe, pull requests merged in 2020-03, with the labels that each got.

#1234 Remove extract_pulse_time_around_peak
  ctapipe/image/extractor.py
Labels: ready for review

#1228 Make subarray a required argument to CameraCalibrator and ImageExtractor
  ctapipe/calib/camera/calibrator.py
  ctapipe/calib/camera/tests/test_calibrator.py
  ctapipe/image/extractor.py
  ctapipe/image/tests/test_extractor.py
  ctapipe/tools/bokeh/file_viewer.py
  examples/load_one_event.py
  examples/plot_array_hillas.py
  examples/plot_showers_in_nominal.py
  examples/plot_theta_square.py
  examples/simple_event_writer.py
  examples/simple_pipeline.py
  examples/stereo_reconstruction.py
Labels: ready for review, refactoring

#1233 Improvement of integration_correction testing, implementation, and docstring
  ctapipe/calib/camera/calibrator.py
  ctapipe/calib/camera/tests/test_calibrator.py
Labels: algorithm, ready for review

#1227 Move pulse shape attributes from mc container to CameraGeometry
  ctapipe/calib/camera/calibrator.py
  ctapipe/calib/camera/tests/test_calibrator.py
  ctapipe/image/geometry_converter_hex.py
  ctapipe/instrument/camera.py
  ctapipe/instrument/tests/test_camera.py
  ctapipe/io/containers.py
  ctapipe/io/hessioeventsource.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_simteleventsource.py
Labels: ready for review, refactoring

#1242 Improvements to ImageExtractor wrt integration_correction and sampling rate
  ctapipe/calib/camera/calibrator.py
  ctapipe/calib/camera/flatfield.py
  ctapipe/calib/camera/pedestals.py
  ctapipe/calib/camera/tests/test_calibrator.py
  ctapipe/calib/camera/tests/test_flatfield.py
  ctapipe/calib/camera/tests/test_pedestals.py
  ctapipe/image/extractor.py
  ctapipe/image/tests/test_extractor.py
  ctapipe/tools/display_dl1.py
Labels: design problem, enhancement, ready for review, refactoring

#1131 Cleaning for biggest cluster
  ctapipe/image/cleaning.py
  ctapipe/image/tests/test_cleaning.py
Labels: algorithm, cleaning, ready for review
