Repository cta-observatory/ctapipe, pull requests merged in 2021-04, with the labels that each got.

#1677 Fix some documentation warnings
  ctapipe/core/traits.py
  docs/ctapipe_api/containers.rst
  docs/ctapipe_api/containers/index.rst
  docs/ctapipe_api/core/traits.rst
  docs/ctapipe_api/index.rst
Labels: documentation, fix

#1659 Use tqdm.auto
  ctapipe/tools/display_events_single_tel.py
  ctapipe/tools/dl1_merge.py
  ctapipe/tools/muon_reconstruction.py
  ctapipe/utils/download.py
  examples/simple_event_writer.py
Labels: ready for review

#1661 Allow specifying extractors per telescope, fixes #1660
  ctapipe/calib/camera/calibrator.py
  ctapipe/calib/camera/tests/test_calibrator.py
  ctapipe/image/reducer.py
  ctapipe/tools/display_integrator.py
Labels: calibration, ready for review

#1667 Remove DL1Writer.setup, just properly initialize in __init__
  ctapipe/io/dl1writer.py
  ctapipe/io/tests/test_dl1writer.py
Labels: ready for review

#1681 Fix syntax typo in call of TwoPassWindowSum with 2ndPass disabled
  ctapipe/image/extractor.py
  ctapipe/image/tests/test_extractor.py
Labels: bug, calibration, fix
