Repository cta-observatory/ctapipe, pull requests merged in 2021-05, with the labels that each got.

#1697 Consistent use of allowed_tels
  ctapipe/instrument/subarray.py
  ctapipe/instrument/tests/test_subarray.py
  ctapipe/io/dl1eventsource.py
  ctapipe/io/eventsource.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_dl1eventsource.py
  ctapipe/io/tests/test_simteleventsource.py
  ctapipe/reco/tests/test_hillas_intersection.py
  ctapipe/tools/display_events_single_tel.py
  ctapipe/tools/display_summed_images.py
  docs/examples/InstrumentDescription.ipynb
  docs/tutorials/calibrated_data_exploration.ipynb
  docs/tutorials/coordinates_example.ipynb
Labels: API change, Breaking change, subarrays

#1698 Fix bugs in TwoPassWindowSum and define better unit-test
  ctapipe/image/extractor.py
  ctapipe/image/tests/test_extractor.py
Labels: calibration, fix

#1712 Fix ctapipe-merge with --allowed-tels
  ctapipe/core/traits.py
  ctapipe/io/eventsource.py
  ctapipe/tools/dl1_merge.py
  docs/conf.py
Labels: bug

#1673 DL2 data model and output
  ctapipe/containers.py
  ctapipe/io/__init__.py
  ctapipe/io/datalevels.py
  ctapipe/io/datawriter.py
  ctapipe/io/dl1eventsource.py
  ctapipe/io/hdf5tableio.py
  ctapipe/io/metadata.py
  ctapipe/io/tableio.py
  ctapipe/io/tests/test_datawriter.py
  ctapipe/io/tests/test_hdf5.py
  ctapipe/io/tests/test_metadata.py
  ctapipe/reco/hillas_intersection.py
  ctapipe/reco/hillas_reconstructor.py
  ctapipe/reco/impact.py
  ctapipe/reco/reco_algorithms.py
  ctapipe/reco/tests/test_ImPACT.py
  ctapipe/tools/dl1_merge.py
  ctapipe/tools/stage1.py
  docs/ctapipe_api/io/index.rst
  docs/data_models/dl1.rst
  docs/examples/table_writer_reader.ipynb
  examples/stage1_config.json
Labels: API change, data model change, refactoring

#1675 Implement a shower processor
  ctapipe/core/qualityquery.py
  ctapipe/reco/__init__.py
  ctapipe/reco/shower_processor.py
  ctapipe/reco/tests/test_shower_processor.py
  docs/ctapipe_api/reco/index.rst
Labels: enhancement, reconstruction
