Repository cta-observatory/ctapipe, pull requests merged in 2022-08, with the labels that each got.

#1973 ObsConfig data model
  ctapipe/containers.py
  ctapipe/io/datawriter.py
  ctapipe/io/eventsource.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_event_source.py
  ctapipe/io/toymodel.py
  ctapipe/tools/merge.py
  ctapipe/tools/tests/test_merge.py
  ctapipe/tools/tests/test_process.py
  docs/bibliography.rst
Labels: new functionality, data model change

#1887 Fix Container.as_dict for case of flatten=True and add_prefix=True
  ctapipe/core/container.py
  ctapipe/core/tests/test_container.py
Labels: fix

#2056 Fix camera rotation in examples/camera_rotation.py
  examples/camera_rotation.py
Labels: bug, ready for review, fix
