Repository cta-observatory/ctapipe, pull requests merged in 2022-11, with the labels that each got.

#2098 Speed up rotations, closes #2097
  ctapipe/coordinates/ground_frames.py
  ctapipe/coordinates/tests/test_coordinates.py
Labels: coordinates

#2131 Support different frames for set_line_hillas
  ctapipe/visualization/mpl_array.py
Labels: enhancement, coordinates, visualisation

#2136 Implement stereo trigger for subarray triggers
  ctapipe/instrument/__init__.py
  ctapipe/instrument/tests/test_trigger.py
  ctapipe/instrument/trigger.py
  ctapipe/tools/process.py
Labels: enhancement
