Repository cta-observatory/ctapipe, pull requests merged in 2022-06, with the labels that each got.

#1919 Print version info in pytest header
  ctapipe/conftest.py
  environment.yml
  setup.cfg
  setup.py
Labels: ready for review

#1905 Minor visual bugfix: better html repr for Tool and Component
  ctapipe/core/component.py
  ctapipe/core/container.py
  ctapipe/core/tool.py
  ctapipe/io/tableloader.py
  setup.py
Labels: ready for review, fix

#1911 improve array display
  ctapipe/coordinates/__init__.py
  ctapipe/coordinates/ground_frames.py
  ctapipe/coordinates/tests/test_coordinates.py
  ctapipe/instrument/subarray.py
  ctapipe/visualization/mpl_array.py
Labels: enhancement, ready for review

#1925 Better error message in case unknown telescopes are selected, fixes #1924
  ctapipe/instrument/__init__.py
  ctapipe/instrument/subarray.py
  ctapipe/instrument/tests/test_subarray.py
Labels: fix

#1929 Support reading files created with `extract_calibevent`
  ctapipe/io/datawriter.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_simteleventsource.py
  environment.yml
  setup.py
Labels: enhancement

#1932 Add overwrite option to write_table
  ctapipe/instrument/subarray.py
  ctapipe/io/astropy_helpers.py
  ctapipe/io/tests/test_write_table.py
Labels: enhancement

#1934 Load all dl2 available groups in TableLoader
  ctapipe/io/tableloader.py
  ctapipe/io/tests/test_table_loader.py
  docs/tutorials/ctapipe_overview.ipynb
Labels: API change

#1893 Store true_image_sum also when true image is not written
  ctapipe/containers.py
  ctapipe/io/astropy_helpers.py
  ctapipe/io/datawriter.py
  ctapipe/tools/merge.py
  ctapipe/tools/tests/test_merge.py
  ctapipe/utils/arrays.py
  ctapipe/utils/tests/test_arrays.py
Labels: ready for review, fix

#1889 Improved configuration of reference metadata
  ctapipe/io/datawriter.py
  ctapipe/io/metadata.py
  ctapipe/io/tests/test_datawriter.py
  ctapipe/tools/process.py
Labels: new functionality

#1899 compute impact distance to shower axis
  ctapipe/conftest.py
  ctapipe/containers.py
  ctapipe/coordinates/__init__.py
  ctapipe/coordinates/tests/test_coordinates.py
  ctapipe/io/datawriter.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tableloader.py
  ctapipe/io/tests/conftest.py
  ctapipe/io/tests/test_datawriter.py
  ctapipe/io/tests/test_table_loader.py
  ctapipe/reco/__init__.py
  ctapipe/reco/hillas_reconstructor.py
  ctapipe/reco/impact_distance.py
  ctapipe/reco/shower_processor.py
  ctapipe/reco/tests/test_impact_distance.py
  ctapipe/resources/base_config.yaml
  ctapipe/resources/image_modification_config.json
  ctapipe/resources/stage1_config.json
  ctapipe/resources/stage1_config.toml
  ctapipe/resources/stage1_config.yaml
  ctapipe/resources/stage2_config.json
  ctapipe/resources/stage2_config.yaml
  ctapipe/resources/training_config.json
  ctapipe/resources/training_config.yaml
  ctapipe/tools/process.py
  ctapipe/tools/tests/test_process.py
  docs/tutorials/ctapipe_overview.ipynb
Labels: ready for review, new functionality, data model change

#1950 Simplify units code in subarray
  ctapipe/instrument/subarray.py
Labels: maintentance

#1943 Add QualityQuery.get_table_mask, compile python code
  ctapipe/core/provenance.py
  ctapipe/core/qualityquery.py
  ctapipe/core/tests/test_qualityquery.py
  ctapipe/image/image_processor.py
  ctapipe/reco/reco_algorithms.py
  ctapipe/reco/tests/test_HillasReconstructor.py
  ctapipe/reco/tests/test_shower_processor.py
  ctapipe/resources/base_config.yaml
  ctapipe/resources/image_modification_config.json
  ctapipe/resources/stage1_config.json
  ctapipe/resources/stage1_config.toml
  ctapipe/resources/stage2_config.json
  ctapipe/resources/training_config.json
Labels: API change

#1958 fixed bug that prevented printing of QualityQuery
  ctapipe/core/qualityquery.py
  ctapipe/core/tests/test_qualityquery.py
Labels: fix

#1956 Hash rounded versions of floats for CameraGeometry
  ctapipe/instrument/camera/geometry.py
Labels: fix

#1952 Create a fresh ArrayEventContainer for each event in SimTelEventSource
  ctapipe/io/simteleventsource.py
Labels: maintentance

#1970 Create a fresh ArrayEventContainer for each event in HDF5EventSource
  ctapipe/io/hdf5eventsource.py
Labels: maintentance

#1940 Read dl2 in hdf5eventsource
  ctapipe/conftest.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/tests/test_hdf5eventsource.py
Labels: enhancement

#1945 Ignore containers and maps by default in HDF5Writer
  ctapipe/io/datawriter.py
  ctapipe/io/hdf5tableio.py
Labels: refactoring
