Repository cta-observatory/ctapipe, pull requests merged in 2022-04, with the labels that each got.

#1854 Implement public interface for 2d index to/from id
  ctapipe/instrument/camera/geometry.py
  ctapipe/instrument/camera/image_conversion.py
  ctapipe/instrument/camera/tests/test_image_conversion.py
Labels: ready for review

#1869 Only upload codecov from one build
  .github/workflows/ci.yml
Labels: ready for review

#1875 Fix bug in ShowerProcessor / HillasReconstructor not using QualityQuery correctly, add support for HillasIntersection in ShowerProcessor
  ctapipe/reco/__init__.py
  ctapipe/reco/hillas_intersection.py
  ctapipe/reco/hillas_reconstructor.py
  ctapipe/reco/impact.py
  ctapipe/reco/reco_algorithms.py
  ctapipe/reco/shower_processor.py
  ctapipe/reco/tests/test_HillasReconstructor.py
  ctapipe/reco/tests/test_hillas_intersection.py
  ctapipe/reco/tests/test_reconstruction_methods.py
  ctapipe/reco/tests/test_shower_processor.py
  ctapipe/tools/process.py
  ctapipe/tools/tests/resources/image_modification_config.json
  ctapipe/tools/tests/resources/stage1_config.json
  ctapipe/tools/tests/resources/stage2_config.json
  ctapipe/tools/tests/resources/training_config.json
  docs/tutorials/ctapipe_overview.ipynb
  docs/tutorials/index.rst
  docs/tutorials/theta_square.ipynb
Labels: Breaking change

#1856 allow YAML and TOML config files and multiple configs
  ctapipe/core/tool.py
  ctapipe/resources/base_config.yaml
  ctapipe/resources/image_modification_config.json
  ctapipe/resources/stage1_config.json
  ctapipe/resources/stage1_config.toml
  ctapipe/resources/stage1_config.yaml
  ctapipe/resources/stage2_config.json
  ctapipe/resources/stage2_config.yaml
  ctapipe/resources/training_config.json
  ctapipe/resources/training_config.yaml
  ctapipe/tools/quickstart.py
  ctapipe/tools/tests/test_merge.py
  ctapipe/tools/tests/test_process.py
  environment.yml
  setup.py
Labels: new functionality

#1897 Fix HDF5EventSource.len to take max_events into account
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/tests/test_hdf5eventsource.py
Labels: bug
