Repository cta-observatory/ctapipe, pull requests merged in 2022-12, with the labels that each got.

#2152 fix import error in metadata: fails on systems without `pwd`
  ctapipe/io/metadata.py
Labels: fix

#2161 Improve likelihood muon intensity fitter
  ctapipe/image/muon/intensity_fitter.py
  ctapipe/image/pixel_likelihood.py
Labels: enhancement, muons

#2176 Run changelog check only on PRs, add support for no-changelog-needed …
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
Labels: no-changelog-needed
