Repository cta-observatory/ctapipe, pull requests merged in 2022-07, with the labels that each got.

#1968 Maintain event order of input file in TableLoader, fixes #1966
  ctapipe/conftest.py
  ctapipe/io/tableloader.py
  ctapipe/io/tests/test_table_loader.py
Labels: enhancement

#1987 Fix comparison of timestamps in calibration code
  ctapipe/calib/camera/flatfield.py
  ctapipe/calib/camera/pedestals.py
Labels: bug

#1988 Improve units code in hillas_parameters
  ctapipe/image/hillas.py
Labels: enhancement

#1976 recursively validate containers
  ctapipe/core/container.py
  ctapipe/core/tests/test_container.py
  examples/load_one_event.py
Labels: enhancement

#1991 Replace deepcopying defaults with default_factory
  ctapipe/containers.py
  ctapipe/core/container.py
  ctapipe/core/tests/test_container.py
  docs/examples/containers.ipynb
Labels: performance, Breaking change, IO

#1672 Add another cleaning method in cleaning.py
  ctapipe/image/cleaning.py
  ctapipe/image/tests/test_cleaning.py
Labels: new functionality

#1949 Rework container prefix handling
  ctapipe/containers.py
  ctapipe/core/container.py
  ctapipe/core/tests/test_container.py
  ctapipe/image/image_processor.py
  ctapipe/io/datawriter.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/hdf5tableio.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tableloader.py
  ctapipe/io/tests/test_datawriter.py
  ctapipe/io/tests/test_hdf5.py
  ctapipe/io/tests/test_hdf5eventsource.py
  ctapipe/io/tests/test_table_loader.py
  ctapipe/reco/hillas_intersection.py
  ctapipe/reco/hillas_reconstructor.py
  ctapipe/reco/impact.py
  ctapipe/reco/shower_processor.py
  ctapipe/tools/tests/test_process.py
Labels: data model change

#1923 Store both equivalent and effective focal length in OpticsDescription, add __slots__
  ctapipe/conftest.py
  ctapipe/core/traits.py
  ctapipe/instrument/__init__.py
  ctapipe/instrument/optics.py
  ctapipe/instrument/subarray.py
  ctapipe/instrument/tests/test_optics.py
  ctapipe/instrument/tests/test_subarray.py
  ctapipe/io/datawriter.py
  ctapipe/io/eventseeker.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tableloader.py
  ctapipe/io/tests/test_datawriter.py
  ctapipe/io/tests/test_eventseeker.py
  ctapipe/io/tests/test_prod2.py
  ctapipe/io/tests/test_simteleventsource.py
  ctapipe/reco/tests/test_HillasReconstructor.py
  ctapipe/reco/tests/test_reconstruction_methods.py
  ctapipe/tools/tests/test_process.py
  ctapipe/tools/tests/test_tools.py
  docs/conf.py
  examples/load_one_event.py
Labels: Breaking change, data model change

#2001 Add dl2 datalevel in hdf5 source, add datalevel tests
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/tests/test_hdf5eventsource.py
Labels: bug

#1880 added a better template for release-drafter
  .github/release-drafter.yml
Labels: enhancement, documentation

#2004 Fix datalevels
  ctapipe/io/datawriter.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/metadata.py
  ctapipe/io/tests/test_metadata.py
  ctapipe/tools/merge.py
Labels: bug, data model change

#2009 Fixed Typo in docstring
  ctapipe/image/cleaning.py
Labels: documentation

#2010 Add methods to read run config and shower distribution to `TableLoader`
  ctapipe/io/tableloader.py
  ctapipe/io/tests/test_table_loader.py
Labels: new functionality

#2013 Fix TableLoader reading empty table
  ctapipe/instrument/subarray.py
  ctapipe/io/tableloader.py
  ctapipe/io/tests/test_table_loader.py
Labels: bug

#1998 Remove restriction on existing file in `EventSource.input_url`, fixes #1821
  ctapipe/io/eventsource.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/simteleventsource.py
Labels: fix

#1985 Use pytest fixtures in unit tests instead of `from_name` methods
  ctapipe/calib/camera/tests/test_flatfield.py
  ctapipe/calib/camera/tests/test_pedestals.py
  ctapipe/conftest.py
  ctapipe/core/tests/test_component.py
  ctapipe/image/hillas.py
  ctapipe/image/muon/tests/test_intensity_fit.py
  ctapipe/image/muon/tests/test_ring_fitter.py
  ctapipe/image/tests/test_cleaning.py
  ctapipe/image/tests/test_concentration.py
  ctapipe/image/tests/test_extractor.py
  ctapipe/image/tests/test_hillas.py
  ctapipe/image/tests/test_image_cleaner_component.py
  ctapipe/image/tests/test_leakage.py
  ctapipe/image/tests/test_modifications.py
  ctapipe/image/tests/test_morphology.py
  ctapipe/image/tests/test_reducer.py
  ctapipe/image/tests/test_sliding_window_correction.py
  ctapipe/image/tests/test_timing_parameters.py
  ctapipe/image/tests/test_toy.py
  ctapipe/instrument/camera/tests/test_geometry.py
  ctapipe/instrument/camera/tests/test_readout.py
  ctapipe/instrument/subarray.py
  ctapipe/instrument/tests/test_optics.py
  ctapipe/instrument/tests/test_subarray.py
  ctapipe/instrument/tests/test_telescope.py
  ctapipe/io/tests/test_toysource.py
  ctapipe/reco/tests/test_HillasReconstructor.py
  ctapipe/visualization/tests/test_mpl.py
  docs/ctapipe_api/instrument/camera_geometry.rst
  docs/ctapipe_api/instrument/camera_readout.rst
  docs/ctapipe_api/instrument/camerageometry_example.py
  docs/examples/Tools.ipynb
  docs/examples/camera_display.ipynb
  docs/examples/convert_images_to_2d.ipynb
  docs/examples/dilate_image.ipynb
  docs/tutorials/coordinates_example.ipynb
  docs/tutorials/ctapipe_overview.ipynb
  examples/camera_animation.py
  examples/camera_display_multi.py
  examples/camera_norms.py
  examples/camera_rotation.py
  examples/highlight_pixel.py
  examples/plot_all_cameras.py
  examples/plot_camera_frames.py
  examples/plot_hillas_parameters.py
Labels: API change, refactoring

#2003 Rework h5 metadata
  ctapipe/conftest.py
  ctapipe/core/container.py
  ctapipe/io/astropy_helpers.py
  ctapipe/io/datawriter.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/hdf5tableio.py
  ctapipe/io/tableio.py
  ctapipe/io/tests/test_astropy_helpers.py
  ctapipe/io/tests/test_datawriter.py
  ctapipe/io/tests/test_hdf5.py
  setup.cfg
Labels: Breaking change, data model change

#2014 ExpressionEngine for QualityQuery and FeatureGenerator
  ctapipe/core/expression_engine.py
  ctapipe/core/feature_generator.py
  ctapipe/core/qualityquery.py
  ctapipe/core/tests/test_feature_generator.py
  ctapipe/core/tests/test_qualityquery.py
  ctapipe/core/traits.py
  docs/conf.py
Labels: refactoring

#2018 Get reference_location and optics/camera name from simtel metadata if available
  ctapipe/instrument/guess.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_simteleventsource.py
Labels: new functionality

#2032 Remove support for by_type split files
  ctapipe/conftest.py
  ctapipe/io/datawriter.py
  ctapipe/io/tableloader.py
  ctapipe/io/tests/test_table_loader.py
Labels: Breaking change, maintentance

#2023 Add abstract InvalidPixelHandler and NeighborAverage implementation, apply in CameraCalibrator and TwoPassWindowSum. Pass invalid pixels to extractors.
  .pre-commit-config.yaml
  ctapipe/calib/camera/__init__.py
  ctapipe/calib/camera/calibrator.py
  ctapipe/calib/camera/flatfield.py
  ctapipe/calib/camera/pedestals.py
  ctapipe/calib/camera/tests/test_calibrator.py
  ctapipe/calib/camera/tests/test_flatfield.py
  ctapipe/calib/camera/tests/test_pedestals.py
  ctapipe/core/traits.py
  ctapipe/image/__init__.py
  ctapipe/image/extractor.py
  ctapipe/image/image_processor.py
  ctapipe/image/invalid_pixels.py
  ctapipe/image/reducer.py
  ctapipe/image/tests/test_extractor.py
  ctapipe/image/tests/test_invalid_pixels.py
  ctapipe/image/tests/test_sliding_window_correction.py
  ctapipe/io/simteleventsource.py
  docs/ctapipe_api/image/index.rst
  docs/ctapipe_api/image/invalid_pixels.rst
  setup.cfg
Labels: calibration, new functionality

#2019 Add pixel, channel, sample information to CameraReadout, update OpticsDescription
  ctapipe/conftest.py
  ctapipe/image/tests/test_hillas.py
  ctapipe/instrument/__init__.py
  ctapipe/instrument/camera/description.py
  ctapipe/instrument/camera/geometry.py
  ctapipe/instrument/camera/readout.py
  ctapipe/instrument/camera/tests/test_description.py
  ctapipe/instrument/camera/tests/test_geometry.py
  ctapipe/instrument/camera/tests/test_readout.py
  ctapipe/instrument/conftest.py
  ctapipe/instrument/guess.py
  ctapipe/instrument/optics.py
  ctapipe/instrument/subarray.py
  ctapipe/instrument/telescope.py
  ctapipe/instrument/tests/test_optics.py
  ctapipe/instrument/tests/test_subarray.py
  ctapipe/instrument/tests/test_telescope.py
  ctapipe/io/datawriter.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_simteleventsource.py
  ctapipe/tools/dump_instrument.py
  ctapipe/utils/datasets.py
  ctapipe/visualization/mpl_camera.py
  docs/tutorials/coordinates_example.ipynb
  docs/tutorials/ctapipe_overview.ipynb
  examples/plot_showers_in_nominal.py
  examples/simple_event_writer.py
  examples/stereo_reconstruction.py
Labels: Breaking change, data model change

#1885 Fix writing and merging of dl2 statistics, fixes #1884
  ctapipe/tools/merge.py
  ctapipe/tools/process.py
  ctapipe/tools/tests/test_merge.py
Labels: bug

#2040 updated incorrect comments in base_config.yaml
  ctapipe/resources/base_config.yaml
Labels: documentation

#1766 Remove cutflow
  ctapipe/utils/__init__.py
  ctapipe/utils/cutflow.py
  ctapipe/utils/tests/test_CutFlow.py
Labels: refactoring, Breaking change

#2045 Use tel_id consistently (replacing telid -> tel_id), fixes #1457
  ctapipe/calib/camera/calibrator.py
  ctapipe/calib/camera/tests/test_calibrator.py
  ctapipe/core/traits.py
  ctapipe/image/extractor.py
  ctapipe/image/reducer.py
  ctapipe/image/tests/test_extractor.py
  ctapipe/image/tests/test_reducer.py
  ctapipe/image/tests/test_sliding_window_correction.py
  ctapipe/tools/display_dl1.py
  examples/calc_pedestals.py
Labels: refactoring

#2046 Use n_ prefix consistently, (rename all num_ to n_), fixes #986
  ctapipe/calib/camera/flatfield.py
  ctapipe/calib/camera/pedestals.py
  ctapipe/calib/camera/tests/test_flatfield.py
  ctapipe/calib/camera/tests/test_pedestals.py
  ctapipe/containers.py
  ctapipe/core/provenance.py
  ctapipe/image/cleaning.py
  ctapipe/image/extractor.py
  ctapipe/image/morphology.py
  ctapipe/image/muon/intensity_fitter.py
  ctapipe/image/muon/tests/test_muon_fitting.py
  ctapipe/image/tests/test_cleaning.py
  ctapipe/image/tests/test_image_processor.py
  ctapipe/instrument/guess.py
  ctapipe/instrument/optics.py
  ctapipe/instrument/subarray.py
  ctapipe/instrument/tests/test_optics.py
  ctapipe/instrument/tests/test_subarray.py
  ctapipe/io/datawriter.py
  ctapipe/io/eventseeker.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_datawriter.py
  ctapipe/io/tests/test_simteleventsource.py
  ctapipe/io/tests/test_table_loader.py
  ctapipe/reco/reco_algorithms.py
  ctapipe/resources/base_config.yaml
  ctapipe/resources/image_modification_config.json
  ctapipe/resources/stage1_config.json
  ctapipe/resources/stage1_config.toml
  ctapipe/resources/stage2_config.json
  ctapipe/resources/training_config.json
  ctapipe/tools/muon_reconstruction.py
  ctapipe/utils/unstructured_interpolator.py
  ctapipe/visualization/mpl_array.py
  ctapipe/visualization/tests/test_mpl.py
  docs/examples/InstrumentDescription.ipynb
  docs/tutorials/calibrated_data_exploration.ipynb
  examples/array_display.py
  examples/plot_array_hillas.py
Labels: Breaking change, data model change
