Repository cta-observatory/ctapipe, pull requests merged in 2022-09, with the labels that each got.

#2069 Fix tables.Node.__del__ throwing exceptions on interpreter exit when writing index tables, fixes #2067
  ctapipe/io/datawriter.py
Labels: fix

#2072 Fix unreachable assertion in Provenance unit test
  ctapipe/core/tests/test_provenance.py
Labels: missing tests, fix

#2047 add --datamodel option to ctapipe-info
  ctapipe/tools/info.py
Labels: new functionality

#2060 Use _impact_ instead of _tel_, fixes #2051
  ctapipe/io/datawriter.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/tests/test_hdf5eventsource.py
  ctapipe/io/tests/test_table_loader.py
  ctapipe/reco/shower_processor.py
  ctapipe/tools/tests/test_merge.py
Labels: data model change

#2073 Improve ShowerProcessor API, fixes #2071
  ctapipe/reco/hillas_intersection.py
  ctapipe/reco/hillas_reconstructor.py
  ctapipe/reco/reco_algorithms.py
  ctapipe/reco/shower_processor.py
  ctapipe/reco/tests/test_HillasReconstructor.py
  ctapipe/reco/tests/test_hillas_intersection.py
  ctapipe/reco/tests/test_shower_processor.py
  ctapipe/resources/base_config.yaml
  ctapipe/resources/image_modification_config.json
  ctapipe/resources/stage1_config.json
  ctapipe/resources/stage2_config.json
  ctapipe/resources/training_config.json
  ctapipe/tools/process.py
Labels: API change

#2036 Vectorize operations in HillasReconstructor
  ctapipe/coordinates/__init__.py
  ctapipe/coordinates/ground_frames.py
  ctapipe/coordinates/nominal_frame.py
  ctapipe/coordinates/telescope_frame.py
  ctapipe/reco/hillas_reconstructor.py
  ctapipe/reco/tests/test_HillasReconstructor.py
  ctapipe/reco/tests/test_reconstruction_methods.py
Labels: optimization

#2085 Fix warnings from deploy workflow
  .github/workflows/deploy.yml
  setup.cfg
Labels: maintenance

#2000 Atmosphere models for h_max to X_max conversion
  ctapipe/atmosphere.py
  ctapipe/instrument/atmosphere.py
  ctapipe/io/datawriter.py
  ctapipe/io/eventsource.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_simteleventsource.py
  ctapipe/tests/test_atmosphere.py
  docs/conf.py
  docs/ctapipe_api/atmosphere/index.rst
Labels: physics, new functionality
