Repository cta-observatory/ctapipe, pull requests merged in 2022-02, with the labels that each got.

#1834 show Frame in CameraGeometry repr
  ctapipe/instrument/camera/geometry.py
Labels: ready for review

#1837 Rename DL1EventSource to HDF5EventSource, add support for reading R1 waveforms as written by DataWriter
  ctapipe/io/__init__.py
  ctapipe/io/datawriter.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/conftest.py
  ctapipe/io/tests/test_datawriter.py
  ctapipe/io/tests/test_hdf5eventsource.py
  ctapipe/tools/dl1_merge.py
  ctapipe/tools/process.py
  docs/ctapipe_api/io/index.rst
Labels: Breaking change

#1835 Raise error for missing focal length
  ctapipe/coordinates/camera_frame.py
  ctapipe/coordinates/tests/test_coordinates.py
Labels: ready for review

#1844 Remove print statements from hdf5eventsource
  ctapipe/io/hdf5eventsource.py
Labels: maintentance

#1816 Implement treatment of invalid values in FixedPointColumnTransform, fixes #1815
  ctapipe/io/datawriter.py
  ctapipe/io/tableio.py
  ctapipe/io/tests/test_column_transforms.py
  ctapipe/io/tests/test_hdf5.py
Labels: bug, ready for review
