Repository cta-observatory/ctapipe, pull requests merged in 2023-03, with the labels that each got.

#2271 Update pre-commit to isort 5.12.0
  .pre-commit-config.yaml
Labels: maintenance, no-changelog-needed

#2256 CEP-001: Definition of the proposal process
  docs/development/ceps/accepted/.keep
  docs/development/ceps/accepted/cep-001.rst
  docs/development/ceps/drafts/.keep
  docs/development/ceps/index.rst
  docs/development/ceps/rejected/.keep
  docs/development/index.rst
Labels: enhancement, proposal, documentation, no-changelog-needed

#2276 Use pre-commit/action
  .github/workflows/ci.yml
  .github/workflows/lint.yml
Labels: no-changelog-needed

#2281 require lint CI before testing
  .github/workflows/ci.yml
  .github/workflows/lint.yml
Labels: no-changelog-needed

#2286 Add missing enter_context for TableLoader in train tools
  ctapipe/tools/train_disp_reconstructor.py
  ctapipe/tools/train_energy_regressor.py
  ctapipe/tools/train_particle_classifier.py
Labels: maintenance, no-changelog-needed

#2290 Render changelog for 0.18.1
  CHANGES.rst
  docs/changes/2261.bugfix.rst
  docs/changes/2287.bugfix.rst
  docs/changes/2288.bugfix.rst
Labels: no-changelog-needed

#2266 Remove or move examples to documentation
  .github/workflows/ci.yml
  docs/changes/2266.maintenance.rst
  docs/ctapipe_api/coordinates/index.rst
  docs/ctapipe_api/coordinates/plot_camera_frames.py
  docs/ctapipe_api/visualization/index.rst
  docs/examples/InstrumentDescription.ipynb
  docs/examples/Tools.ipynb
  docs/examples/array_display.ipynb
  docs/examples/camera_display.ipynb
  docs/examples/containers.ipynb
  docs/examples/convert_images_to_2d.ipynb
  docs/examples/dilate_image.ipynb
  docs/examples/index.rst
  docs/examples/nd_interpolation.ipynb
  docs/examples/provenance.ipynb
  docs/examples/table_writer_reader.ipynb
  environment.yml
  examples/README.rst
  examples/array_display.py
  examples/calc_pedestals.py
  examples/camera_animation.py
  examples/camera_display_multi.py
  examples/camera_norms.py
  examples/camera_rotation.py
  examples/coordinate_transformations.py
  examples/highlight_pixel.py
  examples/instrument_info.py
  examples/load_one_event.py
  examples/plot_array_hillas.py
  examples/plot_hillas_parameters.py
  examples/plot_showers_in_nominal.py
  examples/plot_theta_square.py
  examples/simple_event_writer.json
  examples/simple_event_writer.py
  examples/stereo_reconstruction.py
  examples/tool_example.py
  setup.cfg
Labels: documentation

#2298 Fix status of CEP-001, add link to PR
  docs/development/ceps/accepted/cep-001.rst
Labels: documentation, no-changelog-needed

#2299 Adapt default config for flashcam, bring in line with current grid production
  ctapipe/resources/base_config.yaml
Labels: maintenance, no-changelog-needed

#2300 Render 0.19 changelog using towncrier
  CHANGES.rst
  docs/changes/2188.feature.rst
  docs/changes/2266.maintenance.rst
  docs/changes/2293.api.rst
  docs/changes/2295.maintenance.rst
Labels: documentation, no-changelog-needed

#2302 Install ffmpeg on readthedocs
  .readthedocs.yml
Labels: no-changelog-needed
