Repository cta-observatory/ctapipe, pull requests merged in 2023-01, with the labels that each got.

#2186 Add changelogs for PRs merged since 0.17.0
  .github/workflows/ci.yml
  CHANGES.rst
  docs/changelog.rst
  docs/changes/1767.feature.rst
  docs/changes/2000.feature.rst
  docs/changes/2096.feature.rst
  docs/changes/2120.feature.rst
  docs/changes/2121.feature.rst
  docs/changes/2126.optimization.rst
  docs/changes/2133.feature.rst
  docs/changes/2134.bug.rst
  docs/changes/2136.feature.rst
  docs/changes/2140.feature.rst
  docs/changes/2155.bug.rst
  docs/changes/2163.bug.rst
  docs/changes/2166.maintenance.rst
  docs/changes/2171.bug.rst
  docs/changes/2172.feature.rst
  docs/changes/2173.bug.rst
  docs/changes/2175.api.rst
  pyproject.toml
Labels: no-changelog-needed

#2191 Raise error if run_tool encounters non-zero exit code and raises is True
  ctapipe/core/tests/test_run_tool.py
  ctapipe/core/tests/test_tool.py
  ctapipe/core/tool.py
  ctapipe/tools/tests/test_process.py
Labels: maintenance, no-changelog-needed

#2192 Create proper links to the PR in changelog
  pyproject.toml
Labels: documentation, no-changelog-needed

#2198 Fix frame name in coordinates warning
  ctapipe/coordinates/__init__.py
Labels: maintenance, no-changelog-needed

#2195 Upload build docs as artifacts in CI
  .github/workflows/ci.yml
Labels: maintenance, no-changelog-needed

#1926 Tool exit stack
  ctapipe/core/tool.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/tools/apply_models.py
  ctapipe/tools/display_dl1.py
  ctapipe/tools/process.py
  ctapipe/tools/tests/test_tools.py
  docs/changes/1926.feature.rst
Labels: refactoring

#2202 Rename towncrier bug to bugfix
  docs/changes/2134.bugfix.rst
  docs/changes/2155.bugfix.rst
  docs/changes/2163.bugfix.rst
  docs/changes/2171.bugfix.rst
  docs/changes/2173.bugfix.rst
  pyproject.toml
Labels: no-changelog-needed

#2190 Refactor initialization of telescope parameters, move to own module
  ctapipe/core/__init__.py
  ctapipe/core/component.py
  ctapipe/core/telescope_component.py
  ctapipe/core/tests/test_telescope_component.py
  ctapipe/core/tests/test_traits.py
  ctapipe/core/traits.py
  ctapipe/image/cleaning.py
  ctapipe/image/modifications.py
  docs/ctapipe_api/core/index.rst
Labels: maintenance, no-changelog-needed

#2217 Add option to configure ml prefixes
  ctapipe/reco/sklearn.py
  ctapipe/tools/apply_models.py
  docs/changes/2217.feature.rst
Labels: new functionality

#2225 Move test to correct module
  ctapipe/core/tests/test_tool.py
  ctapipe/core/tool.py
Labels: maintenance, no-changelog-needed

#2223 Use weakref.proxy where parent=self.
  ctapipe/core/component.py
  ctapipe/io/tests/test_event_source.py
  ctapipe/reco/sklearn.py
  docs/changes/2223.maintenance.rst
Labels: maintenance

#2222 Fix numba version to 0.56
  environment.yml
  setup.cfg
Labels: no-changelog-needed

#2180 Fix docstring in ImageProcessor
  ctapipe/image/image_processor.py
Labels: maintenance, no-changelog-needed

#2215 Fix sonarqube issues
  ctapipe/image/muon/tests/test_intensity_fit.py
  ctapipe/utils/template_network_interpolator.py
Labels: maintenance, no-changelog-needed

#2232 Use https links where possible
  ctapipe/coordinates/nominal_frame.py
  ctapipe/coordinates/telescope_frame.py
  ctapipe/core/component.py
  ctapipe/core/tool.py
  ctapipe/io/tests/test_metadata.py
  ctapipe/tools/utils.py
  ctapipe/utils/astro.py
  ctapipe/visualization/mpl_camera.py
  docs/conf.py
  docs/development/code-guidelines.rst
  docs/development/style-guide.rst
  docs/development/support-libraries.rst
  docs/index.rst
  docs/make.bat
  docs/references.txt
  docs/tutorials/coordinates_example.ipynb
  docs/tutorials/raw_data_exploration.ipynb
Labels: maintenance, no-changelog-needed

#2213 Consistent overwrite
  ctapipe/core/tests/test_tool.py
  ctapipe/core/tool.py
  ctapipe/tools/apply_models.py
  ctapipe/tools/dump_triggers.py
  ctapipe/tools/merge.py
  ctapipe/tools/muon_reconstruction.py
  ctapipe/tools/process.py
  ctapipe/tools/tests/test_tools.py
  ctapipe/tools/train_disp_reconstructor.py
  ctapipe/tools/train_energy_regressor.py
  ctapipe/tools/train_particle_classifier.py
  docs/changes/2213.api.rst
Labels: optimization, maintenance, IO

#2101 Use entry_points for plugins
  .github/ISSUE_TEMPLATE/base.md
  .github/workflows/ci.yml
  ctapipe/core/component.py
  ctapipe/core/plugins.py
  ctapipe/core/traits.py
  ctapipe/io/__init__.py
  ctapipe/io/eventsource.py
  ctapipe/io/tests/test_plugin.py
  ctapipe/reco/reconstructor.py
  ctapipe/reco/tests/test_reconstructor.py
  ctapipe/tools/info.py
  ctapipe/tools/tests/test_process.py
  docs/changes/2101.api.rst
  docs/changes/2101.feature.rst
  docs/ctapipe_api/io/index.rst
  setup.cfg
  test_plugin/ctapipe_test_plugin/__init__.py
  test_plugin/pyproject.toml
  test_plugin/setup.py
Labels: refactoring, installation

#2168 Make muon analysis part of the processing tool
  ctapipe/conftest.py
  ctapipe/containers.py
  ctapipe/image/muon/__init__.py
  ctapipe/image/muon/processor.py
  ctapipe/image/muon/ring_fitter.py
  ctapipe/image/muon/tests/test_processor.py
  ctapipe/image/muon/tests/test_ring_fitter.py
  ctapipe/io/datawriter.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/tableloader.py
  ctapipe/io/tests/test_hdf5eventsource.py
  ctapipe/io/tests/test_table_loader.py
  ctapipe/resources/base_config.yaml
  ctapipe/tools/merge.py
  ctapipe/tools/muon_reconstruction.py
  ctapipe/tools/process.py
  ctapipe/tools/tests/test_merge.py
  ctapipe/tools/tests/test_process.py
  ctapipe/tools/tests/test_tools.py
  docs/changes/2168.api.rst
  docs/ctapipe_api/image/muon.rst
  setup.cfg
Labels: muons, API change, ready for review, Breaking change
