Repository cta-observatory/ctapipe, pull requests merged in 2023-11, with the labels that each got.

#2447 Bump setuptools and setuptools scm versions
  .github/workflows/ci.yml
  pyproject.toml
Labels: no-changelog-needed

#2443 Improve column names for disp
  ctapipe/containers.py
  ctapipe/io/datawriter.py
  ctapipe/io/hdf5eventsource.py
  ctapipe/io/tests/test_hdf5eventsource.py
  ctapipe/reco/sklearn.py
  ctapipe/tools/tests/test_apply_models.py
  ctapipe/tools/tests/test_process_ml.py
  docs/changes/2443.datamodel.rst
Labels: data model change

#2458 Fix coverage report not being found by codecov
  .github/workflows/ci.yml
Labels: maintenance, no-changelog-needed

#2448 Removed stray : from ctapipe.io page
  docs/api-reference/io/index.rst
Labels: no-changelog-needed, documentation-only

#2435 Rename single changelog file
  CHANGES.rst
  docs/changes/2388.bug.rst
Labels: no-changelog-needed

#2460 Use editable install to fix coverage
  .github/workflows/ci.yml
  ctapipe/image/muon/tests/test_intensity_fit.py
Labels: maintenance, no-changelog-needed

#2469 Fix CI after pytest-xdist update
  ctapipe/core/tests/test_provenance.py
Labels: maintenance, no-changelog-needed

#2462 Fix indentation in docs resulting in wrong rendering
  ctapipe/image/pixel_likelihood.py
Labels: documentation, no-changelog-needed, documentation-only
