Repository cta-observatory/ctapipe, pull requests merged in 2023-12, with the labels that each got.

#2475 Support for astropy 6
  docs/changes/2475.feature.rst
  environment.yml
  examples/tutorials/ctapipe_overview.py
  examples/tutorials/theta_square.py
  setup.cfg
Labels: maintenance

#2464 Properly transform between camera and telescope frame in muon fitter
  ctapipe/image/muon/intensity_fitter.py
  ctapipe/image/muon/tests/test_intensity_fit.py
  docs/changes/2464.bugfix.rst
Labels: bug

#2432 Change definition of leakage_pixel_{1,2}
  ctapipe/image/leakage.py
  ctapipe/image/tests/test_leakage.py
  docs/changes/2432.api.rst
Labels: data model change

#2456 Update and add missing docstrings related to ML functionalities
  ctapipe/reco/sklearn.py
  ctapipe/reco/stereo_combination.py
  ctapipe/tools/train_disp_reconstructor.py
  ctapipe/tools/train_energy_regressor.py
  ctapipe/tools/train_particle_classifier.py
  docs/changes/2456.optimization.rst
Labels: documentation-only

#2419 Fix docstring of EventSource
  ctapipe/core/component.py
  ctapipe/io/eventsource.py
Labels: documentation, no-changelog-needed
