Repository cta-observatory/ctapipe, pull requests merged in 2023-10, with the labels that each got.

#2412 Add more nitpick ignores to fix docs build after traitlets update
  docs/conf.py
Labels: maintenance, no-changelog-needed, documentation-only

#2411 Add option to override obs_id in SimTelEventSource
  ctapipe/containers.py
  ctapipe/io/simteleventsource.py
  ctapipe/io/tests/test_simteleventsource.py
  docs/changes/2411.features.rst
Labels: enhancement, data model change, IO

#2397 Use intmin for invalid pixel positions, allow empty arguments
  ctapipe/instrument/camera/geometry.py
  ctapipe/instrument/camera/tests/test_geometry.py
  docs/changes/2397.api.rst
Labels: enhancement, instrument

#2408 Fix broken urls in README
  README.rst
  docs/conf.py
Labels: no-changelog-needed, documentation-only

#2420 Add docstring for ctapipe-train-disp-reconstructor
  ctapipe/tools/train_disp_reconstructor.py
  docs/api-reference/tools/index.rst
  docs/changes/2420.bugfix.rst
Labels: documentation-only

#2227 run test only if labels don't contain 'documentation'
  .github/workflows/ci.yml
Labels: no-changelog-needed, documentation-only
