Repository cta-observatory/ctapipe, pull requests merged in 2023-02, with the labels that each got.

#2244 Raise error in case expected telescope-data is missing in HDF5EventSource
  ctapipe/io/hdf5eventsource.py
  docs/changes/2244.api.rst
Labels: API change

#2245 Notify users about `test_plugin` install
  ctapipe/io/tests/test_plugin.py
  ctapipe/reco/tests/test_reconstructor.py
  ctapipe/tools/tests/test_process.py
  docs/getting_started/index.rst
Labels: no-changelog-needed

#2243 Fix wrong overwrite config in train_* tools
  ctapipe/conftest.py
  ctapipe/tools/train_disp_reconstructor.py
  ctapipe/tools/train_energy_regressor.py
  ctapipe/tools/train_particle_classifier.py
Labels: no-changelog-needed

#2247 Add rng attribute back to TrainEnergyRegressor
  ctapipe/tools/tests/test_train.py
  ctapipe/tools/train_energy_regressor.py
Labels: bug, no-changelog-needed

#2249 Refactor apply tool to use HDF5Merger, read data only once
  ctapipe/core/feature_generator.py
  ctapipe/io/tableloader.py
  ctapipe/io/tests/test_table_loader.py
  ctapipe/tools/apply_models.py
  ctapipe/tools/tests/test_apply_models.py
Labels: enhancement, no-changelog-needed

#2251 Render 0.18 changelog using towncrier
  .mailmap
  CHANGES.rst
  docs/changes/1767.feature.rst
  docs/changes/1926.feature.rst
  docs/changes/2000.feature.rst
  docs/changes/2096.feature.rst
  docs/changes/2101.api.rst
  docs/changes/2101.feature.rst
  docs/changes/2120.feature.rst
  docs/changes/2121.feature.rst
  docs/changes/2126.optimization.rst
  docs/changes/2133.feature.rst
  docs/changes/2134.bugfix.rst
  docs/changes/2136.feature.rst
  docs/changes/2138.feature.rst
  docs/changes/2140.feature.rst
  docs/changes/2144.maintenance.rst
  docs/changes/2155.bugfix.rst
  docs/changes/2163.bugfix.rst
  docs/changes/2166.maintenance.rst
  docs/changes/2167.feature.rst
  docs/changes/2168.api.rst
  docs/changes/2171.bugfix.rst
  docs/changes/2172.feature.rst
  docs/changes/2173.bugfix.rst
  docs/changes/2175.api.rst
  docs/changes/2179.feature.rst
  docs/changes/2187.bugfix.rst
  docs/changes/2189.bugfix.rst
  docs/changes/2197.bugfix.rst
  docs/changes/2203.feature.rst
  docs/changes/2213.api.rst
  docs/changes/2217.feature.rst
  docs/changes/2223.maintenance.rst
  docs/changes/2229.api.rst
  docs/changes/2241.api.rst
  docs/changes/2244.api.rst
Labels: no-changelog-needed

#2252 Fix rst warnings for README, use linter in CI to prevent in future
  .github/workflows/ci.yml
  README.rst
Labels: maintenance, no-changelog-needed

#2253 Add pypi badge to readme
  README.rst
Labels: no-changelog-needed

#2254 Update CI config after default branch renaming
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/release_drafter.yml
Labels: no-changelog-needed

#2259 Fix deprecation warning due to pkg_resources
  ctapipe/core/provenance.py
  ctapipe/tools/info.py
  ctapipe/tools/utils.py
  ctapipe/utils/datasets.py
  pyproject.toml
Labels: maintenance, no-changelog-needed

#2263 Added favicon
  docs/_static/favicon.ico
  docs/conf.py
Labels: no-changelog-needed

#2220 Make devs aware of debugging and `ipdb` in docs
  docs/getting_started/index.rst
Labels: documentation, no-changelog-needed
