Repository cta-observatory/ctapipe, pull requests merged in 2023-09, with the labels that each got.

#2376 Use int minval instead -1 for invalid telescope ids in SubarrayDescription.tel_index_array, improve docstrings
  ctapipe/instrument/subarray.py
  docs/changes/2376.api.rst
Labels: API change, maintenance

#2304 cep 2: event structure
  docs/developer-guide/ceps/index.rst
  docs/developer-guide/ceps/proposed/cep-002.rst
Labels: no-changelog-needed

#2394 Add changelog for 0.20.0
  CHANGES.rst
  docs/changes/2265.bugfix.rst
  docs/changes/2328.feature.rst
  docs/changes/2338.feature.rst
  docs/changes/2342.maintenance.rst
  docs/changes/2343.feature.rst
  docs/changes/2373.maintenance.rst
  docs/changes/2375.api.rst
  docs/changes/2376.api.rst
  docs/changes/2381.feature.rst
  docs/changes/2384.api.rst
  docs/changes/2386.feature.rst
Labels: no-changelog-needed

#2377 Convert all notebooks to sphinx gallery format
  .gitignore
  docs/Makefile
  docs/conf.py
  docs/conftest.py
  docs/user-guide/examples/InstrumentDescription.ipynb
  docs/user-guide/examples/Tools.ipynb
  docs/user-guide/examples/array_display.ipynb
  docs/user-guide/examples/camera_display.ipynb
  docs/user-guide/examples/containers.ipynb
  docs/user-guide/examples/convert_images_to_2d.ipynb
  docs/user-guide/examples/dilate_image.ipynb
  docs/user-guide/examples/index.rst
  docs/user-guide/examples/nd_interpolation.ipynb
  docs/user-guide/examples/provenance.ipynb
  docs/user-guide/examples/table_writer_reader.ipynb
  docs/user-guide/examples_tutorials.rst
  docs/user-guide/index.rst
  docs/user-guide/tutorials/calibrated_data_exploration.ipynb
  docs/user-guide/tutorials/coordinates_example.ipynb
  docs/user-guide/tutorials/ctapipe_handson.ipynb
  docs/user-guide/tutorials/ctapipe_overview.ipynb
  docs/user-guide/tutorials/index.rst
  docs/user-guide/tutorials/raw_data_exploration.ipynb
  docs/user-guide/tutorials/theta_square.ipynb
  environment.yml
  examples/README.rst
  examples/algorithms/README.rst
  examples/algorithms/convert_images_to_2d.py
  examples/algorithms/dilate_image.py
  examples/algorithms/nd_interpolation.py
  examples/core/InstrumentDescription.py
  examples/core/README.rst
  examples/core/command_line_tools.py
  examples/core/config.json
  examples/core/containers.py
  examples/core/provenance.py
  examples/core/table_writer_reader.py
  examples/tutorials/README.rst
  examples/tutorials/calibrated_data_exploration.py
  examples/tutorials/coordinates_example.py
  examples/tutorials/ctapipe_handson.py
  examples/tutorials/ctapipe_overview.py
  examples/tutorials/ground_frame.png
  examples/tutorials/raw_data_exploration.py
  examples/tutorials/theta_square.py
  examples/tutorials/tilted_ground_frame.png
  examples/visualization/README.rst
  examples/visualization/array_display.py
  examples/visualization/camera_display.py
  pyproject.toml
  setup.cfg
Labels: documentation, no-changelog-needed

#2399 Fix docs by adding more traitlets nitpick ignores
  docs/conf.py
Labels: maintenance, no-changelog-needed
