Repository cta-observatory/ctapipe, pull requests merged in 2024-04, with the labels that each got.

#2531 add SonarQube badges & remove codecov
  .github/workflows/ci.yml
  README.rst
Labels: no-changelog-needed, documentation-only

#2536 Fix docs build, use sphinxcontrib-bibtex for bibliography
  .codespell-ignores
  docs/bibliography.rst
  docs/conf.py
  docs/references.bib
  environment.yml
  examples/core/table_writer_reader.py
  pyproject.toml
  src/ctapipe/containers.py
  src/ctapipe/image/cleaning.py
  src/ctapipe/image/muon/fitting.py
  src/ctapipe/image/muon/intensity_fitter.py
  src/ctapipe/image/pixel_likelihood.py
  src/ctapipe/io/metadata.py
  src/ctapipe/reco/hillas_intersection.py
  src/ctapipe/reco/hillas_reconstructor.py
  src/ctapipe/utils/astro.py
Labels: maintenance, no-changelog-needed, documentation-only

#2529 Change R1- and DL0-waveforms shape to (n_channels, n_pixels, n_samples)
  docs/changes/2529.datamodel.rst
  examples/core/table_writer_reader.py
  src/ctapipe/calib/camera/calibrator.py
  src/ctapipe/calib/camera/flatfield.py
  src/ctapipe/calib/camera/gainselection.py
  src/ctapipe/calib/camera/pedestals.py
  src/ctapipe/calib/camera/tests/test_calibrator.py
  src/ctapipe/calib/camera/tests/test_flatfield.py
  src/ctapipe/calib/camera/tests/test_gainselection.py
  src/ctapipe/calib/camera/tests/test_pedestals.py
  src/ctapipe/containers.py
  src/ctapipe/image/extractor.py
  src/ctapipe/image/invalid_pixels.py
  src/ctapipe/image/reducer.py
  src/ctapipe/image/tests/test_extractor.py
  src/ctapipe/image/tests/test_invalid_pixels.py
  src/ctapipe/image/tests/test_reducer.py
  src/ctapipe/image/tests/test_sliding_window_correction.py
  src/ctapipe/image/tests/test_toy.py
  src/ctapipe/image/toymodel.py
  src/ctapipe/io/datawriter.py
  src/ctapipe/io/hdf5eventsource.py
  src/ctapipe/io/simteleventsource.py
  src/ctapipe/io/tests/test_hdf5eventsource.py
  src/ctapipe/io/tests/test_simteleventsource.py
Labels: enhancement, calibration, data model change

#2534 Use macos 14 (apple arm) in CI
  .github/workflows/ci.yml
Labels: maintenance, no-changelog-needed

#2547 Fix CI
  pyproject.toml
  src/ctapipe/io/tests/test_hdf5.py
  src/ctapipe/reco/tests/test_ImPACT.py
Labels: no-changelog-needed

#2550 Prepare changelog for 0.21.0
  CHANGES.rst
  docs/_static/switcher.json
  docs/changes/2214.maintenance.rst
  docs/changes/2305.feature.rst
  docs/changes/2369.feature.rst
  docs/changes/2397.api.rst
  docs/changes/2402.bugfix.rst
  docs/changes/2403.bugfix.rst
  docs/changes/2406.maintenance.rst
  docs/changes/2409.feature.rst
  docs/changes/2414.bugfix.rst
  docs/changes/2418.bugfix.rst
  docs/changes/2420.bugfix.rst
  docs/changes/2421.bugfix.rst
  docs/changes/2422.feature.rst
  docs/changes/2423.optimization.rst
  docs/changes/2429.feature.rst
  docs/changes/2430.feature.rst
  docs/changes/2431.bugfix.rst
  docs/changes/2432.api.rst
  docs/changes/2438.api.rst
  docs/changes/2440.bugfix.rst
  docs/changes/2443.datamodel.rst
  docs/changes/2451.feature.rst
  docs/changes/2455.optimization.rst
  docs/changes/2456.optimization.rst
  docs/changes/2459.maintenance.rst
  docs/changes/2464.bugfix.rst
  docs/changes/2465.api.rst
  docs/changes/2468.optimization.rst
  docs/changes/2470.feature.rst
  docs/changes/2474.maintenance.rst
  docs/changes/2475.feature.rst
  docs/changes/2477.optimization.rst
  docs/changes/2479.feature.rst
  docs/changes/2481.feature.rst
  docs/changes/2482.api.rst
  docs/changes/2483.optimization.rst
  docs/changes/2485.maintenance.rst
  docs/changes/2486.maintenance.rst
  docs/changes/2505.bugfix.rst
  docs/changes/2511.api.rst
  docs/changes/2520.api.rst
  docs/changes/2524.feature.rst
  docs/changes/2526.maintenance.rst
  docs/changes/2529.datamodel.rst
  docs/changes/2537.feature.rst
  docs/changes/2544.bugfix.rst
  docs/changes/2545.optimization.rst
  docs/changes/2549.feature.rst
Labels: no-changelog-needed
