Repository cta-observatory/ctapipe, pull requests merged in 2024-02, with the labels that each got.

#2514 fix some documentation bugs
  docs/api-reference/atmosphere/index.rst
  docs/user-guide/tools.rst
  examples/visualization/camera_display.py
  src/ctapipe/atmosphere.py
  src/ctapipe/coordinates/ground_frames.py
  src/ctapipe/coordinates/nominal_frame.py
  src/ctapipe/core/telescope_component.py
Labels: no-changelog-needed, documentation-only

#2512 Move options from setup.cfg to pyproject.toml
  docs/conf.py
  pyproject.toml
  setup.cfg
Labels: maintenance, no-changelog-needed

#2516 Fix entry point specification
  .github/workflows/ci.yml
  docs/conf.py
  pyproject.toml
  src/ctapipe/core/container.py
Labels: no-changelog-needed
