Repository cta-observatory/ctapipe, pull requests merged in 2024-08, with the labels that each got.

#2590 Update AUTHORS, add to release procedure
  .mailmap
  .pre-commit-config.yaml
  AUTHORS
  docs/developer-guide/maintainer-info.rst
Labels: no-changelog-needed, documentation-only

#2554 Add StatisticsAggregator API
  docs/api-reference/monitoring/aggregator.rst
  docs/api-reference/monitoring/index.rst
  docs/changes/2554.feature.rst
  docs/conf.py
  src/ctapipe/containers.py
  src/ctapipe/image/statistics.py
  src/ctapipe/image/tests/test_statistics.py
  src/ctapipe/monitoring/aggregator.py
  src/ctapipe/monitoring/tests/__init__.py
  src/ctapipe/monitoring/tests/test_aggregator.py
Labels: enhancement, calibration

#2604 OutlierDetector components
  docs/api-reference/monitoring/index.rst
  docs/api-reference/monitoring/outlier.rst
  docs/changes/2604.feature.rst
  src/ctapipe/monitoring/outlier.py
  src/ctapipe/monitoring/tests/test_outlier.py
Labels: calibration
