Repository cta-observatory/ctapipe, pull requests merged in 2024-11, with the labels that each got.

#2625 Add Hipparcos as second star catalog, apply space motion
  .codespell-ignores
  .pre-commit-config.yaml
  docs/changes/2625.api.rst
  docs/changes/2625.features.rst
  pyproject.toml
  src/ctapipe/resources/hipparcos_star_catalog.fits.gz
  src/ctapipe/resources/yale_bright_star_catalog.fits.gz
  src/ctapipe/utils/astro.py
  src/ctapipe/utils/tests/test_astro.py
Labels: coordinates, calibration, new functionality

#2637 Improve changelog checks
  .github/workflows/changelog.yml
  docs/changes/2411.feature.rst
  docs/changes/2609.feature.rst
  docs/changes/2625.feature.rst
Labels: enhancement, fix, no-changelog-needed

#2642 Fix changelog checks
  .github/workflows/changelog.yml
Labels: fix, no-changelog-needed

#2636 Variance calibration
  docs/changes/2636.feature.rst
  src/ctapipe/calib/camera/calibrator.py
  src/ctapipe/calib/camera/tests/test_calibrator.py
Labels: calibration

#2655 Restore reading of pointing for files written with ctapipe<0.21
  src/ctapipe/io/hdf5eventsource.py
  src/ctapipe/io/tests/test_hdf5eventsource.py
  src/ctapipe/tools/tests/test_process.py
Labels: bug, no-changelog-needed

#2654 Prepare 0.23.0
  CHANGES.rst
  docs/changes/2411.feature.rst
  docs/changes/2609.feature.rst
  docs/changes/2625.api.rst
  docs/changes/2625.feature.rst
  docs/changes/2627.bugfix.rst
  docs/changes/2633.api.rst
  docs/changes/2636.feature.rst
  docs/changes/2641.api.rst
  docs/changes/2648.api.rst
  docs/changes/2650.feature.rst
  docs/user-guide/getting-started.rst
Labels: no-changelog-needed, documentation-only

#2656 Update authors and add new version to switcher
  .mailmap
  AUTHORS
  docs/_static/switcher.json
Labels: no-changelog-needed, documentation-only

#2657 Use sphinx-changelog
  .github/workflows/ci.yml
  docs/changelog.rst
  docs/conf.py
  environment.yml
  pyproject.toml
Labels: no-changelog-needed, documentation-only
