Repository cta-observatory/ctapipe, pull requests merged in 2024-07, with the labels that each got.

#2572 Update intersphinx mapping and sphinx-gallery-conf
  docs/conf.py
Labels: documentation, no-changelog-needed

#2578 Run sonar in separate step to enable PRs from forks again
  .github/workflows/ci.yml
  .github/workflows/sonar.yml
  sonar-project.properties
Labels: no-changelog-needed

#2582 Fix filename in sonar action
  .github/workflows/sonar.yml
Labels: no-changelog-needed

#2583 use correct sonar action
  .github/workflows/sonar.yml
Labels: no-changelog-needed

#2584 Fix missing SONAR_HOST_URL
  .github/workflows/ci.yml
  .github/workflows/sonar.yml
Labels: no-changelog-needed

#2585 Fix sonarqube for forks
  .github/workflows/ci.yml
  .github/workflows/sonar.yml
Labels: no-changelog-needed

#2586 Fix sonar
  .github/workflows/sonar.yml
  pyproject.toml
Labels: no-changelog-needed

#2581 Treat deprecation warnings as errors
  pyproject.toml
  src/ctapipe/tools/tests/test_tools.py
Labels: no-changelog-needed

#2541 Implement lstchains image cleaning
  docs/changes/2541.feature.rst
  src/ctapipe/image/cleaning.py
  src/ctapipe/image/extractor.py
  src/ctapipe/image/statistics.py
  src/ctapipe/image/tests/test_cleaning.py
  src/ctapipe/image/tests/test_image_cleaner_component.py
  src/ctapipe/image/tests/test_statistics.py
Labels: enhancement, algorithm, cleaning

#2589 Fix docs build
  docs/conf.py
  pyproject.toml
Labels: no-changelog-needed

#2593 Fix traitlets test by ignoring test modules and _dev_version
  pyproject.toml
  src/ctapipe/tests/test_traitlets_configurable.py
Labels: no-changelog-needed

#2595 Fix provenance in case broken packages are in the environment
  src/ctapipe/core/provenance.py
Labels: no-changelog-needed

#2599 Fix deprecation warning in provenance, fixes #2592
  src/ctapipe/core/provenance.py
Labels: no-changelog-needed

#2594 Update exception handling in tools
  docs/changes/2594.optimization.rst
  src/ctapipe/core/tests/test_tool.py
  src/ctapipe/core/tests/test_traits.py
  src/ctapipe/core/tool.py
Labels: enhancement

#2543 Variance extractor
  docs/changes/2543.feature.rst
  src/ctapipe/containers.py
  src/ctapipe/image/extractor.py
  src/ctapipe/image/tests/test_extractor.py
Labels: calibration
