Repository cta-observatory/ctapipe, pull requests merged in 2024-06, with the labels that each got.

#2562 Remove unsed config files for old test and quality control systems
  .codacy.yml
  .landscape.yml
Labels: maintenance, no-changelog-needed

#2566 Feature/custom exit codes in tools
  docs/changes/2566.feature.rst
  src/ctapipe/core/provenance.py
  src/ctapipe/core/tests/test_run_tool.py
  src/ctapipe/core/tool.py
Labels: enhancement

#2570 Prepare changelog for 0.21.2
  CHANGES.rst
  docs/_static/switcher.json
  docs/changes/2560.maintenance.rst
  docs/changes/2566.feature.rst
  docs/changes/2569.bugfix.rst
Labels: no-changelog-needed
