Repository cta-observatory/ctapipe, pull requests merged in 2024-03, with the labels that each got.

#2520 Refactor/rename datawriter options (redux)
  docs/changes/2520.api.rst
  examples/tutorials/ctapipe_overview.py
  examples/tutorials/tableloader_and_eventsources.py
  src/ctapipe/conftest.py
  src/ctapipe/io/datawriter.py
  src/ctapipe/io/tests/conftest.py
  src/ctapipe/io/tests/test_datawriter.py
  src/ctapipe/resources/base_config.yaml
  src/ctapipe/resources/image_modification_config.json
  src/ctapipe/resources/ml_preprocessing_config.json
  src/ctapipe/resources/ml_preprocessing_config.yaml
  src/ctapipe/resources/stage1_config.json
  src/ctapipe/resources/stage1_config.toml
  src/ctapipe/resources/stage1_config.yaml
  src/ctapipe/resources/stage2_config.json
  src/ctapipe/resources/stage2_config.yaml
  src/ctapipe/tools/process.py
  src/ctapipe/tools/tests/test_process.py
Labels: API change

#2523 Update python version in deploy config
  .github/workflows/deploy.yml
Labels: maintenance, no-changelog-needed

#2511 Change `ImageCleaner` API
  docs/changes/2511.api.rst
  src/ctapipe/calib/camera/tests/test_calibrator.py
  src/ctapipe/conftest.py
  src/ctapipe/image/cleaning.py
  src/ctapipe/image/image_processor.py
  src/ctapipe/image/reducer.py
Labels: enhancement, API change, dl1

#2463 Add configuration for using CTAO sonarqube to check code
  .github/workflows/ci.yml
  .gitignore
  docs/changes/2214.maintenance.rst
  pyproject.toml
  sonar-project.properties
Labels: no-changelog-needed

#2525 Update sonar key
  sonar-project.properties
Labels: maintenance, no-changelog-needed

#2527 Fix sonar complaining about statements in notebooks
  sonar-project.properties
Labels: maintenance, no-changelog-needed

#2526 Drop python 3.9
  .github/workflows/ci.yml
  .readthedocs.yaml
  docs/changes/2526.maintenance.rst
  docs/conf.py
  examples/algorithms/nd_interpolation.py
  pyproject.toml
  sonar-project.properties
  src/ctapipe/atmosphere.py
  src/ctapipe/coordinates/impact_distance.py
  src/ctapipe/core/container.py
  src/ctapipe/core/plugins.py
  src/ctapipe/core/telescope_component.py
  src/ctapipe/core/tool.py
  src/ctapipe/core/traits.py
  src/ctapipe/image/extractor.py
  src/ctapipe/image/invalid_pixels.py
  src/ctapipe/instrument/camera/geometry.py
  src/ctapipe/instrument/camera/readout.py
  src/ctapipe/instrument/subarray.py
  src/ctapipe/instrument/tests/__init__.py
  src/ctapipe/io/astropy_helpers.py
  src/ctapipe/io/datawriter.py
  src/ctapipe/io/eventseeker.py
  src/ctapipe/io/eventsource.py
  src/ctapipe/io/hdf5eventsource.py
  src/ctapipe/io/hdf5merger.py
  src/ctapipe/io/hdf5tableio.py
  src/ctapipe/io/metadata.py
  src/ctapipe/io/simteleventsource.py
  src/ctapipe/io/tableloader.py
  src/ctapipe/io/tests/test_eventseeker.py
  src/ctapipe/io/tests/test_hdf5.py
  src/ctapipe/io/tests/test_write_table.py
  src/ctapipe/io/toymodel.py
  src/ctapipe/reco/preprocessing.py
  src/ctapipe/reco/sklearn.py
  src/ctapipe/tests/test_traitles_configurable.py
  src/ctapipe/tools/dump_instrument.py
  src/ctapipe/tools/tests/test_train.py
  src/ctapipe/tools/utils.py
Labels: maintenance
