Repository cta-observatory/ctapipe, pull requests merged in 2024-12, with the labels that each got.

#2659 Fix error in ctapipe-process in case telescope event is missing true image
  docs/changes/2659.bugfix.rst
  src/ctapipe/io/simteleventsource.py
  src/ctapipe/io/tableloader.py
  src/ctapipe/io/tests/test_datawriter.py
  src/ctapipe/io/tests/test_hdf5.py
  src/ctapipe/io/tests/test_simteleventsource.py
  src/ctapipe/tools/tests/test_process.py
Labels: sim_telarray

#2622 Fix dtype of tel_id in subarray hdf table
  src/ctapipe/instrument/subarray.py
Labels: no-changelog-needed

#2669 Update image.cleaning docs
  docs/references.bib
  src/ctapipe/image/__init__.py
  src/ctapipe/image/cleaning.py
Labels: documentation, no-changelog-needed

#2667 Prepare 0.23.1
  CHANGES.rst
  docs/_static/switcher.json
  docs/changes/2639.feature.rst
  docs/changes/2658.bugfix.rst
  docs/changes/2659.bugfix.rst
  docs/changes/2662.bugfix.rst
  docs/changes/2664.maintenance.rst
  docs/changes/2666.bugfix.rst
Labels: no-changelog-needed, documentation-only

#2671 Fix sonar for pull requests
  .github/workflows/sonar.yml
Labels: maintenance, no-changelog-needed, documentation-only
