Repository cta-observatory/ctapipe, pull requests merged in 2024-01, with the labels that each got.

#2482 Move `TableLoader` traits to `read_...`-methods
  ctapipe/instrument/tests/test_trigger.py
  ctapipe/io/tableloader.py
  ctapipe/io/tests/test_table_loader.py
  ctapipe/tools/apply_models.py
  ctapipe/tools/tests/test_apply_models.py
  ctapipe/tools/tests/test_merge.py
  ctapipe/tools/tests/test_process.py
  ctapipe/tools/train_disp_reconstructor.py
  ctapipe/tools/train_energy_regressor.py
  ctapipe/tools/train_particle_classifier.py
  ctapipe/tools/utils.py
  docs/changes/2482.api.rst
  examples/tutorials/ctapipe_overview.py
  examples/tutorials/tableloader_and_eventsources.py
Labels: API change, documentation, IO

#2466 Fix some minor issues found by sonarqube
  ctapipe/io/tests/test_metadata.py
  ctapipe/visualization/bokeh.py
  docs/conf.py
Labels: maintenance, no-changelog-needed

#2487 Update citation year and add link
  README.rst
Labels: no-changelog-needed, documentation-only

#2488 Prevent import of ctapipe.image at import time of ctapipe.io
  ctapipe/io/toymodel.py
Labels: optimization, no-changelog-needed

#2490 Add config to let dependabot update github actions
  .github/dependabot.yml
  .readthedocs.yaml
  pyproject.toml
  setup.cfg
Labels: maintenance, no-changelog-needed, documentation-only

#2400 Accept CEP 002
  .gitignore
  docs/developer-guide/ceps/accepted/cep-002.rst
  docs/developer-guide/ceps/drafts/.keep
  docs/developer-guide/ceps/index.rst
  docs/developer-guide/ceps/proposed/cep-003-remove-image-parameters-in-camera-frame.rst
Labels: no-changelog-needed, documentation-only

#2496 pin scikit-learn to < 1.4, breaks with astropy tables
  setup.cfg
Labels: maintenance, no-changelog-needed, dependencies

#2500 Fix pydata sphinx theme is not safe for parallel writing warning
  Makefile
Labels: no-changelog-needed

#2502 Fix wrong branch name in README
  README.rst
Labels: no-changelog-needed, documentation-only
