Repository cta-observatory/ctapipe, pull requests merged in 2025-02, with the labels that each got.

#2687 Add CI job testing on python 3.13
  .github/workflows/ci.yml
Labels: maintenance, no-changelog-needed

#2643 PSF model
  docs/changes/2643.feature.rst
  docs/references.bib
  src/ctapipe/instrument/__init__.py
  src/ctapipe/instrument/optics.py
  src/ctapipe/instrument/tests/test_psf_model.py
Labels: enhancement, module:calib, new functionality

#2634 Chunk interpolation to select calibration data
  docs/changes/2634.feature.rst
  src/ctapipe/monitoring/__init__.py
  src/ctapipe/monitoring/interpolation.py
  src/ctapipe/monitoring/tests/test_interpolator.py
Labels: module:calib, new functionality

#2700 Fix name of cut-optimizer tool in example config
  src/ctapipe/resources/optimize_cuts.yaml
Labels: no-changelog-needed

#2697 Use sysmon coverage
  .github/workflows/ci.yml
Labels: no-changelog-needed
