Repository cta-observatory/ctapipe, pull requests merged in 2025-06, with the labels that each got.

#2762 Two small CameraDisplay fixes: subfigures and optional psi_uncertainty
  docs/changes/2762.bugfix.rst
  src/ctapipe/visualization/mpl_camera.py
  src/ctapipe/visualization/tests/test_mpl.py
Labels: bug

#2766 Prepare release 0.26.0
  .github/workflows/ci.yml
  .mailmap
  AUTHORS
  CHANGES.rst
  docs/_static/switcher.json
  docs/changes/2436.feature.rst
  docs/changes/2736.api.rst
  docs/changes/2753.feature.rst
  docs/changes/2757.feature.rst
  docs/changes/2762.bugfix.rst
  src/ctapipe/tools/tests/test_train.py
Labels: no-changelog-needed

#2776 add HDF5Merger to the pix stats tool
  docs/changes/2776.feature.rst
  src/ctapipe/tools/calculate_pixel_stats.py
  src/ctapipe/tools/tests/test_calculate_pixel_stats.py
Labels: module:tools

#2788 Update pyirf to 0.13
  pyproject.toml
Labels: no-changelog-needed
