Repository cta-observatory/ctapipe, pull requests merged in 2025-04, with the labels that each got.

#2729 Prepare 0.24.0
  AUTHORS
  CHANGES.rst
  docs/_static/switcher.json
  docs/changes/2473.feature.rst
  docs/changes/2628.feature.rst
  docs/changes/2634.feature.rst
  docs/changes/2643.feature.rst
  docs/changes/2670.feature.rst
  docs/changes/2673.bugfix.rst
  docs/changes/2688.bugfix.rst
  docs/changes/2691.maintenance.rst
  docs/changes/2692.bugfix.rst
  docs/changes/2696.feature.rst
  docs/changes/2703.bugfix.rst
  docs/changes/2707.datamodel.rst
  docs/changes/2709.feature.rst
  docs/changes/2715.bugfix.rst
  docs/changes/2722.feature.rst
  docs/changes/2725.api.rst
Labels: no-changelog-needed

#2732 Force absences of units for skewness and excess_kurtosis
  docs/changes/2732.bugfix.rst
  src/ctapipe/image/muon/features.py
  src/ctapipe/image/muon/tests/test_muon_features.py
Labels: fix

#2734 Docs: Rename data model -> data format, update
  docs/api-reference/io/index.rst
  docs/user-guide/data_format/index.rst
  docs/user-guide/index.rst
Labels: no-changelog-needed, documentation-only

#2744 Do not require subarray pointing in HDF5EventSource
  docs/changes/2744.bugfix.rst
  src/ctapipe/io/hdf5eventsource.py
  src/ctapipe/io/tests/test_hdf5eventsource.py
Labels: bug

#2746 Render changelog for v0.25.1
  CHANGES.rst
  docs/changes/2741.bugfix.rst
  docs/changes/2744.bugfix.rst
Labels: no-changelog-needed, documentation-only

#2747 Fix setuptools deprecation warnings
  pyproject.toml
Labels: maintenance, no-changelog-needed
