Repository cta-observatory/ctapipe, pull requests merged in 2025-03, with the labels that each got.

#2710 Fix sonar for PRs from forks
  .github/workflows/sonar.yml
Labels: no-changelog-needed

#2713 Fix checkout cleaning up coverage report in sonar ci
  .github/workflows/sonar.yml
Labels: maintenance, no-changelog-needed

#2715 Processing gain-selected dl1 data with the pixel stats tool
  docs/changes/2715.bugfix.rst
  src/ctapipe/monitoring/outlier.py
  src/ctapipe/monitoring/tests/test_outlier.py
  src/ctapipe/tools/calculate_pixel_stats.py
  src/ctapipe/tools/tests/test_calculate_pixel_stats.py
Labels: bug

#2670 Muon parameters update
  docs/changes/2670.feature.rst
  src/ctapipe/containers.py
  src/ctapipe/image/muon/features.py
  src/ctapipe/image/muon/processor.py
  src/ctapipe/image/muon/tests/test_muon_features.py
Labels: module:calib

#2619 Add CI run running on oldest supported versions of core dependencies
  .github/workflows/ci.yml
  environment.yml
  pyproject.toml
Labels: no-changelog-needed

#2688 Make sure config is fully serialized to provenance json
  docs/changes/2688.bugfix.rst
  src/ctapipe/core/provenance.py
  src/ctapipe/core/tests/test_tool.py
  src/ctapipe/core/tests/test_traits.py
  src/ctapipe/core/traits.py
Labels: bug, module:provenance
