Repository cta-observatory/ctapipe, pull requests merged in 2025-01, with the labels that each got.

#2677 Fix broken Numpy style guide link.
  docs/developer-guide/style-guide.rst
Labels: no-changelog-needed, documentation-only

#2679 Update the link to the CI status badge in README
  README.rst
Labels: no-changelog-needed, documentation-only

#2682 Add explicit cast necessary in numpy >=2.1
  .readthedocs.yaml
  docs/changes/2682.maintenance.rst
  src/ctapipe/calib/camera/calibrator.py
  src/ctapipe/io/simteleventsource.py
Labels: maintenance

#2684 Prepare 0.23.2
  .mailmap
  AUTHORS
  CHANGES.rst
  docs/_static/switcher.json
  docs/changes/2682.maintenance.rst
  docs/developer-guide/maintainer-info.rst
Labels: no-changelog-needed, documentation-only

#2680 Fill `containers.SimulatedCameraContainer.true_image_sum` in HDF5eventsource
  CHANGES.rst
  src/ctapipe/io/hdf5eventsource.py
Labels: bug, no-changelog-needed

#2686 Make sonar coverage badge link point to coverage
  README.rst
Labels: maintenance, no-changelog-needed, documentation-only

#2628 Stats calc tool
  docs/changes/2628.feature.rst
  docs/user-guide/tools.rst
  pyproject.toml
  src/ctapipe/resources/calculate_pixel_stats.yaml
  src/ctapipe/tools/calculate_pixel_stats.py
  src/ctapipe/tools/quickstart.py
  src/ctapipe/tools/tests/test_calculate_pixel_stats.py
Labels: calibration
